name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env: #define your environment variables
      BASE_URL: ${{vars.BASE_URL}}
      STANDARD_USER: ${{secrets.STANDARD_USER}}
      STANDARD_PASSWORD: ${{secrets.STANDARD_PASSWORD}}
      PROBLEM_USER: ${{secrets.PROBLEM_USER}}
      PROBLEM_PASSWORD: ${{secrets.PROBLEM_PASSWORD}}
      PERFORMANCE_GLITCH_USER: ${{secrets.PERFORMANCE_GLITCH_USER}}
      PERFORMANCE_GLITCH_PASSWORD: ${{secrets.PERFORMANCE_GLITCH_PASSWORD}}
      ERROR_USER: ${{secrets.ERROR_USER}}
      ERROR_PASSWORD: ${{secrets.ERROR_PASSWORD}}
      VISUAL_USER: ${{secrets.VISUAL_USER}}
      VISUAL_PASSWORD: ${{secrets.VISUAL_PASSWORD}}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    # 4. Run tests (must use Allure reporter)
    - name: Run tests and generate report
      run: npx allure run -- npm run test
      # This generates allure-results/ directory and creates allure-report/ with summary.json

    # 5. Post summary to PR
    - name: Run Allure Action
      uses: allure-framework/allure-action@v0
      with:
        report-directory: "./allure-report"
        github-token: ${{ secrets.CF_GITHUB_TOKEN }}
