name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env: #define your environment variables
      BASE_URL: ${{vars.BASE_URL}}
      STANDARD_USER: ${{secrets.STANDARD_USER}}
      STANDARD_PASSWORD: ${{secrets.STANDARD_PASSWORD}}
      PROBLEM_USER: ${{secrets.PROBLEM_USER}}
      PROBLEM_PASSWORD: ${{secrets.PROBLEM_PASSWORD}}
      PERFORMANCE_GLITCH_USER: ${{secrets.PERFORMANCE_GLITCH_USER}}
      PERFORMANCE_GLITCH_PASSWORD: ${{secrets.PERFORMANCE_GLITCH_PASSWORD}}
      ERROR_USER: ${{secrets.ERROR_USER}}
      ERROR_PASSWORD: ${{secrets.ERROR_PASSWORD}}
      VISUAL_USER: ${{secrets.VISUAL_USER}}
      VISUAL_PASSWORD: ${{secrets.VISUAL_PASSWORD}}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    # 4. Run tests (must use Allure reporter)
    - name: Run Playwright tests and generate Allure results
      run: npx playwright test
      # The allure-playwright reporter will automatically create the 'allure-results' directory

    - name: Generate Allure report
      # The 'allure generate' command converts the raw results to an HTML report
      run: npx allure generate allure-results --clean -o allure-report
      # 'continue-on-error: true' is an option to allow subsequent steps to run even if tests fail

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
        # Optional: set a retention period for the artifact
        retention-days: 7
